### ISSUE TITLE
Right servo motor does not function

### ISSUE THREAD

**Issue by jdinka18** [jdinka18/mlschools-robotics#4]
Check the code related to its function for Team 8816. You added it so you do it lol

**Comment by jdinka18** [comment]
Also I can't tell what some parts of your code are doing. Please write some more comments.

**Comment by GeekProgram007** [comment]
I’ll write more comments later, thanks

**Comment by GeekProgram007** [comment]
The code is fine for the servos, it's the wiring that causes the problem. Adding the comments
